### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by jeminh** [exectails/Morrighan#4]
I'm using this to try and connect to Mabicommerce and I am using morrioneclick. I've done admin privileges and everything. However, when I try to log in, it says wrong email or password. I am 100% sure that i am inputting my info correctly. What am I supposed to do?

**Comment by exectails** [comment]
Morrioneclick doesn't work anymore since they removed the in-game login as far as I know. Check the readme for how to connect to NA now with using the Nexon Launcher: https://github.com/exectails/Morrighan#nexon-launcher

**Comment by jeminh** [comment]
I'm sorry but I don't get any of the read me... I'm not sure what im supposed to do after i put morrighan in my game file....

**Comment by exectails** [comment]
Right-click Morrighan.exe in your Mabinogi folder, select "Create shortcut", right-click the new shortcut, and put this as the target:
```text
Morrighan.exe code:1622 ver:143 logip:208.85.109.35 logport:11000 chatip:208.85.109.37 chatport:8002 setting:"file://data/features.xml=Regular, USA" nxlauncher
```
After clicking OK, double-click the shortcut and a window will open, giving you instructions. Follow them and the game should start with Morrighan.

Quick warning, Xcelled hasn't updated MabiCommerce in a while and some information in it are outdated. Because of that the auto detection you're looking for won't work out of the box, you have to update the "op codes" in its options. These change from time to time, but are usually posted in the MabiCommerce thread on MabiMods.

**Comment by exectails** [comment]
Closing this since it should hopefully have been resolved.

**Comment by TheEnziio** [comment]
I followed every step to set up Morrighan, it did register the hash from nxlauncher and launch the client with it, but whenever I hit "Start Mabinogi" it gives me the "Server can't be reached" notice, is this a known issue or am I missing something?

**Comment by exectails** [comment]
@TheEnziio The IPs you are using are presumably outdated, as they changed recently. I updated the readme with the new ones just now, so just update your link/bat with the new IPs and it should hopefully work.
